added failing tests for 5 encoding/decoding related problems
azizkayumov/learning-rust pull request #14
Opened 2022-09-23 05:02 UTC by azizkayumov

This PR:
- [x] adds failing tests for these 5 encoding / decoding related Leetcode problems:
- [x] solves [Decode XORed Array](https://leetcode.com/problems/decode-xored-array/).
- [x] solves [Decompress Run-Length Encoded List](https://leetcode.com/problems/decompress-run-length-encoded-list/). 
- [x] solves [Shuffle String](https://leetcode.com/problems/shuffle-string/).(https://leetcode.com/problems/maximum-number-of-words-found-in-sentences/).
- [x] solves [Decode the Message](https://leetcode.com/problems/decode-the-message/).
- [x] solves [Convert Binary Number in a Linked List to Integer](https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/).

2022-09-26 22:44 UTC, msk requested changes

2022-09-26 22:44 UTC, msk commented on src/decode_message.rs
> +            table.insert(c, letter as char);
This approach requires two searches for key, one for `contains_key` and another for `insert`. Using [`entry`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.entry) would perform a key search only once.

2022-09-26 22:44 UTC, msk commented on src/shuffle_string.rs
> +    for i in 0..indices.len() {
Instead of an index variable `i`, use [`zip`](https://doc.rust-lang.org/std/iter/fn.zip.html) to iterate over two slices simultaneously.

2022-09-27 16:04 UTC, azizkayumov commented on src/shuffle_string.rs
> +    for i in 0..indices.len() {
Thank you for your feedback. Indeed, it looks cleaner with `zip` instead of the indexed `for` loop

2022-09-27 18:13 UTC, msk approved these changes

2022-09-27 18:13 UTC, merged